# Generated by Django 4.0.1 on 2022-01-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('sample_cases', models.CharField(max_length=1024)),
                ('test_cases', models.TextField()),
                ('solution', models.TextField()),
            ],
        ),
    ]
