# Generated by Django 4.0.1 on 2022-01-20 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemlist',
            name='description',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='problemlist',
            name='sample_cases',
            field=models.CharField(max_length=2048),
        ),
        migrations.CreateModel(
            name='AlgoExpertUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=2048)),
                ('solution', models.TextField()),
                ('tier', models.CharField(choices=[('F', 'FREE'), ('P', 'PAID')], max_length=16)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_submission', to='problems.problemlist')),
            ],
        ),
    ]
