# Generated by Django 4.0.1 on 2022-01-20 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problemlist_start_code_problemlist_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problemtags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='problemlist',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'EASY'), ('MEDIUM', 'MEDIUM'), ('HARD', 'HARD'), ('VERY HARD', 'VERY HARD')], default='EASY', max_length=64),
            preserve_default=False,
        ),
    ]
