# Generated by Django 4.0.1 on 2022-01-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0004_problemtags_problemlist_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemlist',
            name='tags',
            field=models.ManyToManyField(to='problems.ProblemTags'),
        ),
    ]
