# Generated by Django 4.0.1 on 2022-01-22 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0007_remove_algoexpertuser_uid_algoexpertuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problemlist',
            name='type',
        ),
        migrations.AddField(
            model_name='problemlist',
            name='tier',
            field=models.CharField(choices=[('F', 'FREE'), ('P', 'PAID')], default='F', max_length=16),
        ),
    ]
